//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutokeyRPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUK_tecnici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AUK_tecnici()
        {
            this.AUK_cantieri = new HashSet<AUK_cantieri>();
            this.PKT_Operatori = new HashSet<PKT_Operatori>();
        }
    
        public int ID { get; set; }
        public string Codice { get; set; }
        public string ragioneSocialeTecnico { get; set; }
        public string cognomeTecnico { get; set; }
        public string nomeTecnico { get; set; }
        public string indirizzo { get; set; }
        public Nullable<int> ID_localita_tecnico { get; set; }
        public Nullable<int> ID_regione { get; set; }
        public string note_tecnico { get; set; }
        public string tel1_tecnico { get; set; }
        public string tel2_tecnico { get; set; }
        public string mail1_tecnico { get; set; }
        public bool is_tecnico { get; set; }
        public bool is_smontatore { get; set; }
        public bool is_controller { get; set; }
        public bool is_perito { get; set; }
        public Nullable<int> ID_valutazioneTecnico { get; set; }
        public Nullable<int> ID_fornitoreTecnico { get; set; }
        public Nullable<int> IDruolo { get; set; }
        public string insertUser { get; set; }
        public bool Is_assicurato { get; set; }
        public bool Is_OnCalendario { get; set; }
        public Nullable<int> ID_taglia { get; set; }
        public Nullable<System.DateTime> dataInizioAttivitaTecnico { get; set; }
        public Nullable<System.DateTime> dataFineAttivitaTecnico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUK_cantieri> AUK_cantieri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PKT_Operatori> PKT_Operatori { get; set; }
    }
}
