//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutokeyRPC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutokeyEntities : DbContext
    {
        public AutokeyEntities()
            : base("name=AutokeyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RPC_Cantieri> RPC_Cantieri { get; set; }
        public virtual DbSet<AUK_cantieri> AUK_cantieri { get; set; }
        public virtual DbSet<AUK_tecnici> AUK_tecnici { get; set; }
        public virtual DbSet<RPC_Lotti> RPC_Lotti { get; set; }
        public virtual DbSet<RPC_Telai> RPC_Telai { get; set; }
        public virtual DbSet<PKT_Operatori> PKT_Operatori { get; set; }
        public virtual DbSet<RPC_FotoXTelaio> RPC_FotoXTelaio { get; set; }
        public virtual DbSet<RPC_telai_vw> RPC_telai_vw { get; set; }
        public virtual DbSet<RPC_Cantieri_vw> RPC_Cantieri_vw { get; set; }
        public virtual DbSet<RPC_Danni> RPC_Danni { get; set; }
        public virtual DbSet<RPC_DanniXTelaio> RPC_DanniXTelaio { get; set; }
        public virtual DbSet<RPC_Gravita> RPC_Gravita { get; set; }
        public virtual DbSet<RPC_Parti> RPC_Parti { get; set; }
        public virtual DbSet<RPC_Cantieri_vw_FABIO> RPC_Cantieri_vw_FABIO { get; set; }
    }
}
