//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutokeyRPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PKT_Operatori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PKT_Operatori()
        {
            this.RPC_Telai = new HashSet<RPC_Telai>();
        }
    
        public string ID { get; set; }
        public Nullable<int> IDTecnici { get; set; }
        public Nullable<int> IDRuolo { get; set; }
    
        public virtual AUK_tecnici AUK_tecnici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RPC_Telai> RPC_Telai { get; set; }
    }
}
