//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutokeyRPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPC_telai_vw
    {
        public int ID { get; set; }
        public int IDCantiere { get; set; }
        public string IDOperatore { get; set; }
        public int IDLotto { get; set; }
        public string Telaio { get; set; }
        public string Descr { get; set; }
        public bool IsFinished { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<int> NumFoto { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string Note { get; set; }
        public string Cantiere { get; set; }
        public string Condizione { get; set; }
        public string DescrModello { get; set; }
        public string Targa { get; set; }
    }
}
