//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutokeyRPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPC_DanniXTelaio
    {
        public int ID { get; set; }
        public int IDTelaio { get; set; }
        public Nullable<int> IDParte { get; set; }
        public Nullable<int> IDDanno { get; set; }
        public Nullable<int> IDGravita { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string NoteDanno { get; set; }
    
        public virtual RPC_Danni RPC_Danni { get; set; }
        public virtual RPC_Gravita RPC_Gravita { get; set; }
        public virtual RPC_Parti RPC_Parti { get; set; }
        public virtual RPC_Telai RPC_Telai { get; set; }
    }
}
