//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutokeyRPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPC_Cantieri
    {
        public int ID { get; set; }
        public int IDCantiere { get; set; }
        public string Descr { get; set; }
    
        public virtual AUK_cantieri AUK_cantieri { get; set; }
        public virtual RPC_Cantieri RPC_Cantieri1 { get; set; }
        public virtual RPC_Cantieri RPC_Cantieri2 { get; set; }
    }
}
